import archivo


def test_sumas(texto, resultado):
    assert archivo.mostrar_fuzz() == [
        "Lorem ipsum dolor sit amet, Fuzz consectetur adipiscing elit. Cras convallis sed dolor at sagittis. Nam ligula mi, egestas ut vulputate vitae, luctus sed lacus. Suspendisse tortor lectus, dignissim sed rutrum ac, imperdiet non dui. Pellentesque interdum lorem urna, sit amet commodo erat blandit id. Fusce mauris sem, facilisis vel pulvinar et, tempor eu enim. Fusce ac justo quis leo volutpat rutrum. Nunc elementum, eros in hendrerit cursus, tellus purus pellentesque nibh, sed congue orci metus vitae orci. Vestibulum condimentum aliquet fermentum. Nullam condimentum, felis non pharetra porta, purus est posuere mauris, id viverra sem lacus a turpis. Phasellus vehicula mi ac orci dictum rutrum. ",
        "Phasellus ut augue sit amet urna fringilla lacinia at at nibh. Morbi eu rhoncus diam, vitae dictum felis. Maecenas et ligula convallis, viverra lacus sit amet, pulvinar nibh. Vivamus placerat magna id augue blandit aliquet. Maecenas eu cursus sapien, eget gravida augue. Praesent at sodales velit, non aliquam nunc. Morbi accumsan ut ipsum non convallis. Donec in libero nec nisl euismod viverra ut ac felis. Nulla facilisi. Mauris condimentum, urna a ullamcorper sodales, lacus metus mattis quam, vel rutrum lorem metus a sem. Vestibulum dignissim augue eget ante aliquam, nec molestie justo lacinia. Vestibulum fuzz eget lorem in nulla consectetur dignissim ut vel turpis. ",
        "Phasellus ut augue sit amet urna fringilla lacinia at at nibh. Morbi eu rhoncus diam, vitae dictum felis. Maecenas et ligula convallis, viverra lacus sit amet, pulvinar nibh. Vivamus placerat magna id augue blandit aliquet. Maecenas eu cursus sapien, eget gravida augue. Praesent at sodales velit, non aliquam nunc. Morbi accumsan ut ipsum non convallis. Donec in libero nec nisl euismod viverra ut ac felis. Nulla facilisi. Mauris condimentum, urna a ullamcorper sodales, lacus metus mattis quam, vel rutrum lorem metus a sem. Vestibulum dignissim augue eget ante aliquam, nec molestie justo lacinia. Vestibulum eget lorem in nulla consectetur dignissim ut vel turpis. Fuzz ",
    ]
